// CODE GENERATED BY SPACE TOOLS. DO NOT EDIT FILE. YOUR CHANGES WILL BE LOST.
import { useState, useEffect, useMemo, useCallback } from "react";
import { Plus, Trash2, Edit3, ChevronDown, ChevronUp, X, CheckCircle, AlertTriangle, XCircle, Zap, Shield, Eye, BarChart3, PieChart, TrendingDown, Calendar, Smartphone, Activity, Brain, ListChecks, Filter, Search, ExternalLink, Sun, Moon } from "lucide-react";

type Category = "Streaming"|"SaaS"|"Utilities"|"Fitness"|"Productivity"|"Entertainment"|"Storage"|"Other";
type Cycle = "Monthly"|"Yearly";
type Status = "Active"|"Paused"|"Cancelled";
type Freq = "Daily"|"Weekly"|"Monthly"|"Rarely"|"Passive";
type Imp = "High"|"Medium"|"Low";
type Diff = "Easy"|"Medium"|"Hard";

interface Sub {
  id: string; name: string; category: Category; cost: number; cycle: Cycle;
  renewal: string; autoRenew: boolean; status: Status; lastUsed: string;
  freq: Freq; importance: Imp; difficulty: Diff; freeAlt: boolean;
  link: string; notes: string;
}

const CATS: Category[] = ["Streaming","SaaS","Utilities","Fitness","Productivity","Entertainment","Storage","Other"];
const CYCLES: Cycle[] = ["Monthly","Yearly"];
const STATUSES: Status[] = ["Active","Paused","Cancelled"];
const FREQS: Freq[] = ["Daily","Weekly","Monthly","Rarely","Passive"];
const IMPS: Imp[] = ["High","Medium","Low"];
const DIFFS: Diff[] = ["Easy","Medium","Hard"];

const CAT_COLORS: Record<Category,string> = {
  Streaming:"#3b82f6",SaaS:"#8b5cf6",Utilities:"#f59e0b",Fitness:"#10b981",
  Productivity:"#6366f1",Entertainment:"#ec4899",Storage:"#14b8a6",Other:"#6b7280"
};

const CAT_ICONS: Record<Category,string> = {
  Streaming:"📺",SaaS:"💻",Utilities:"⚡",Fitness:"💪",Productivity:"📋",Entertainment:"🎮",Storage:"☁️",Other:"📦"
};

function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,8)}
function daysBetween(a:string,b:string){return Math.round((new Date(b).getTime()-new Date(a).getTime())/864e5)}
function today(){return new Date().toISOString().slice(0,10)}

function monthly(s:Sub){return s.cycle==="Monthly"?s.cost:s.cost/12}
function yearly(s:Sub){return s.cycle==="Monthly"?s.cost*12:s.cost}

function wasteScore(s:Sub):number {
  let score=0;
  const daysSince=daysBetween(s.lastUsed,today());
  if(daysSince>30)score+=3;else if(daysSince>14)score+=2;else if(daysSince>7)score+=1;
  if(s.freq==="Rarely")score+=3;else if(s.freq==="Monthly")score+=1;else if(s.freq==="Passive")score+=2;
  if(s.importance==="Low")score+=3;else if(s.importance==="Medium")score+=1;
  if(s.freeAlt)score+=2;
  if(monthly(s)>30)score+=2;else if(monthly(s)>15)score+=1;
  return score;
}

function wasteLevel(s:Sub):"High"|"Medium"|"Low"{const w=wasteScore(s);return w>=8?"High":w>=5?"Medium":"Low"}

function valueScore(s:Sub):number{
  let v=0;
  if(s.freq==="Daily")v+=4;else if(s.freq==="Weekly")v+=3;else if(s.freq==="Monthly")v+=2;else if(s.freq==="Passive")v+=1;
  if(s.importance==="High")v+=4;else if(s.importance==="Medium")v+=2;
  if(monthly(s)<10)v+=2;else if(monthly(s)<25)v+=1;
  if(!s.freeAlt)v+=1;
  return v;
}

function valueTier(s:Sub):"Excellent"|"Good"|"Fair"|"Weak"{const v=valueScore(s);return v>=9?"Excellent":v>=7?"Good":v>=4?"Fair":"Weak"}

function recommendation(s:Sub):"cancel"|"review"|"keep"{const w=wasteLevel(s);return w==="High"?"cancel":w==="Medium"?"review":"keep"}

const WC={High:"#ef4444",Medium:"#eab308",Low:"#22c55e"};
const VC={Excellent:"#22c55e",Good:"#3b82f6",Fair:"#eab308",Weak:"#ef4444"};
const RC={cancel:"#ef4444",review:"#eab308",keep:"#22c55e"};

function useSubs():[Sub[],(s:Sub[])=>void]{
  const[subs,setSubs]=useState<Sub[]>([]);
  useEffect(()=>{try{const d=localStorage.getItem("zoscription");if(d)setSubs(JSON.parse(d))}catch{}},[]);
  const save=useCallback((s:Sub[])=>{setSubs(s);localStorage.setItem("zoscription",JSON.stringify(s))},[]);
  return[subs,save];
}

function useTheme():[boolean,(v:boolean)=>void]{
  const[light,setLight]=useState(()=>{try{return localStorage.getItem("zosc_theme")==="light"}catch{return false}});
  const toggle=(v:boolean)=>{setLight(v);localStorage.setItem("zosc_theme",v?"light":"dark")};
  return[light,toggle];
}

interface ThemeColors {
  bg: string; bgAlt: string; card: string; cardBorder: string;
  text: string; textDim: string; textMuted: string; textFaint: string;
  inputBg: string; inputBorder: string; inputFocus: string;
  hoverBg: string; divider: string; overlay: string;
  svgStroke: string; barBg: string;
}

const darkTheme: ThemeColors = {
  bg:"#09090b",bgAlt:"#09090b",card:"rgba(24,24,27,0.8)",cardBorder:"#27272a",
  text:"#ffffff",textDim:"#d4d4d8",textMuted:"#71717a",textFaint:"#3f3f46",
  inputBg:"#18181b",inputBorder:"#3f3f46",inputFocus:"#a855f7",
  hoverBg:"rgba(24,24,27,0.5)",divider:"rgba(39,39,42,0.5)",overlay:"rgba(0,0,0,0.7)",
  svgStroke:"#18181b",barBg:"#27272a",
};

const lightTheme: ThemeColors = {
  bg:"#f8fafc",bgAlt:"#ffffff",card:"rgba(255,255,255,0.95)",cardBorder:"#e2e8f0",
  text:"#0f172a",textDim:"#334155",textMuted:"#64748b",textFaint:"#cbd5e1",
  inputBg:"#f1f5f9",inputBorder:"#cbd5e1",inputFocus:"#7c3aed",
  hoverBg:"rgba(241,245,249,0.8)",divider:"rgba(226,232,240,0.5)",overlay:"rgba(0,0,0,0.4)",
  svgStroke:"#ffffff",barBg:"#e2e8f0",
};

function Badge({color,children}:{color:string,children:React.ReactNode}){
  return <span className="px-2 py-0.5 rounded-full text-xs font-bold" style={{background:color+"22",color}}>{children}</span>
}

function Card({children,className="",t}:{children:React.ReactNode,className?:string,t:ThemeColors}){
  return <div className={"rounded-2xl p-5 backdrop-blur-md transition-all duration-300 hover:shadow-lg "+className} style={{background:t.card,border:`1px solid ${t.cardBorder}`,boxShadow:`0 1px 3px rgba(0,0,0,${t===darkTheme?0.3:0.06})`}}>{children}</div>
}

function StatCard({label,value,sub,color="white",t,icon}:{label:string,value:string,sub?:string,color?:string,t:ThemeColors,icon?:React.ReactNode}){
  return <Card t={t}><div className="flex items-start justify-between">
    <div><p className="text-[10px] uppercase tracking-widest font-medium mb-2" style={{color:t.textMuted}}>{label}</p><p className="text-3xl font-black tracking-tight" style={{color}}>{value}</p>{sub&&<p className="text-xs mt-1.5" style={{color:t.textFaint}}>{sub}</p>}</div>
    {icon&&<div className="p-2 rounded-xl" style={{background:color+"15"}}>{icon}</div>}
  </div></Card>
}

function PieChartSVG({data,t}:{data:{label:string,value:number,color:string}[],t:ThemeColors}){
  const total=data.reduce((a,d)=>a+d.value,0);
  if(!total)return <p className="text-sm" style={{color:t.textFaint}}>No data</p>;
  let cum=0;
  const slices=data.filter(d=>d.value>0).map(d=>{
    const start=cum/total*2*Math.PI-Math.PI/2;
    cum+=d.value;
    const end=cum/total*2*Math.PI-Math.PI/2;
    const large=d.value/total>0.5?1:0;
    const x1=50+40*Math.cos(start),y1=50+40*Math.sin(start);
    const x2=50+40*Math.cos(end),y2=50+40*Math.sin(end);
    return{...d,path:`M50,50 L${x1},${y1} A40,40 0 ${large},1 ${x2},${y2} Z`,pct:((d.value/total)*100).toFixed(1)};
  });
  return <div className="flex flex-col sm:flex-row gap-6">
    <div className="relative">
      <svg viewBox="0 0 100 100" className="w-52 h-52 shrink-0 drop-shadow-lg">{slices.map((s,i)=><path key={i} d={s.path} fill={s.color} stroke={t.svgStroke} strokeWidth="0.5" className="hover:opacity-80 transition-opacity cursor-pointer"><title>{s.label}: ${s.value.toFixed(2)}/mo ({s.pct}%)</title></path>)}</svg>
      <div className="absolute inset-0 flex items-center justify-center pointer-events-none"><div className="w-20 h-20 rounded-full backdrop-blur-sm flex items-center justify-center" style={{background:t.bg+"cc"}}><span className="text-xs font-bold" style={{color:t.textDim}}>${total.toFixed(0)}/mo</span></div></div>
    </div>
    <div className="flex flex-col gap-1.5">{slices.map((s,i)=><span key={i} className="flex items-center gap-2 text-xs" style={{color:t.textDim}}><span className="w-3 h-3 rounded-md shrink-0" style={{background:s.color}}/>{s.label} <span style={{color:t.textMuted}}>({s.pct}%)</span></span>)}</div>
  </div>
}

function BarChartSVG({data,height=200,t}:{data:{label:string,value:number,color:string}[],height?:number,t:ThemeColors}){
  const max=Math.max(...data.map(d=>d.value),1);
  if(!data.length)return <p className="text-sm" style={{color:t.textFaint}}>No data</p>;
  const barW=Math.min(40,Math.max(16,(600-data.length*6)/data.length));
  const totalW=data.length*(barW+6)+20;
  return <div className="overflow-x-auto"><svg viewBox={`0 0 ${Math.max(totalW,200)} ${height+40}`} className="w-full" style={{minWidth:Math.max(totalW,200),maxHeight:height+40}}>
    {data.map((d,i)=>{const h=(d.value/max)*(height-20);const x=i*(barW+6)+10;return <g key={i}>
      <rect x={x} y={height-h} width={barW} height={h} fill={d.color} rx={barW/4} className="hover:opacity-80 cursor-pointer transition-opacity"><title>{d.label}: ${d.value.toFixed(2)}/mo</title></rect>
      <text x={x+barW/2} y={height+14} textAnchor="middle" fill={t.textMuted} fontSize="8" transform={`rotate(-30,${x+barW/2},${height+14})`}>{d.label.length>8?d.label.slice(0,8)+"…":d.label}</text>
      <text x={x+barW/2} y={height-h-6} textAnchor="middle" fill={t.textDim} fontSize="7" fontWeight="bold">${d.value.toFixed(0)}</text>
    </g>})}
  </svg></div>
}

function ScatterSVG({data,t}:{data:{label:string,x:number,y:number,color:string}[],t:ThemeColors}){
  const maxX=Math.max(...data.map(d=>d.x),1);const maxY=Math.max(...data.map(d=>d.y),1);
  if(!data.length)return <p className="text-sm" style={{color:t.textFaint}}>No data</p>;
  return <svg viewBox="0 0 300 220" className="w-full max-w-lg">
    <line x1="40" y1="10" x2="40" y2="190" stroke={t.cardBorder} strokeWidth="0.5"/>
    <line x1="40" y1="190" x2="290" y2="190" stroke={t.cardBorder} strokeWidth="0.5"/>
    <text x="165" y="210" textAnchor="middle" fill={t.textMuted} fontSize="9">Cost →</text>
    <text x="12" y="100" textAnchor="middle" fill={t.textMuted} fontSize="9" transform="rotate(-90,12,100)">Value →</text>
    <line x1="40" y1="190" x2="290" y2="10" stroke={t.cardBorder+"33"} strokeWidth="0.5" strokeDasharray="4"/>
    <rect x="42" y="12" width="120" height="88" fill="#22c55e08" rx="4"/><text x="48" y="24" fill="#22c55e44" fontSize="7">High Value / Low Cost ✓</text>
    <rect x="160" y="100" width="128" height="88" fill="#ef444408" rx="4"/><text x="166" y="112" fill="#ef444444" fontSize="7">Low Value / High Cost ✗</text>
    {data.map((d,i)=>{const cx=40+(d.x/maxX)*240;const cy=190-(d.y/maxY)*170;return <g key={i}>
      <circle cx={cx} cy={cy} r={7} fill={d.color} fillOpacity={0.8} className="hover:opacity-60 cursor-pointer transition-opacity"><title>{d.label}: Cost ${d.x.toFixed(2)}, Value {d.y}</title></circle>
      <circle cx={cx} cy={cy} r={7} fill="none" stroke={d.color} strokeWidth="1.5" strokeOpacity="0.3"/>
      <text x={cx} y={cy-11} textAnchor="middle" fill={t.textDim} fontSize="7">{d.label.length>10?d.label.slice(0,10)+"…":d.label}</text>
    </g>})}
  </svg>
}

const EMPTY_SUB:Sub={id:"",name:"",category:"Streaming",cost:0,cycle:"Monthly",renewal:today(),autoRenew:true,status:"Active",lastUsed:today(),freq:"Weekly",importance:"Medium",difficulty:"Easy",freeAlt:false,link:"",notes:""};

function SubForm({sub,onSave,onCancel,t}:{sub:Sub|null,onSave:(s:Sub)=>void,onCancel:()=>void,t:ThemeColors}){
  const[f,setF]=useState<Sub>(sub||{...EMPTY_SUB,id:uid()});
  const u=(k:keyof Sub,v:any)=>setF(p=>({...p,[k]:v}));
  const sel={background:t.inputBg,border:`1px solid ${t.inputBorder}`,color:t.text};
  return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 overflow-y-auto" style={{background:t.overlay}} onClick={onCancel}>
    <div className="rounded-2xl p-6 w-full max-w-lg max-h-[90vh] overflow-y-auto shadow-2xl" style={{background:t.bg,border:`1px solid ${t.cardBorder}`}} onClick={e=>e.stopPropagation()}>
      <div className="flex justify-between items-center mb-5"><h2 className="text-lg font-bold" style={{color:t.text}}>{sub?"Edit":"Add"} Subscription</h2><button onClick={onCancel}><X className="w-5 h-5 hover:opacity-70" style={{color:t.textMuted}}/></button></div>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div className="sm:col-span-2"><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Service Name *</label><input className="w-full rounded-xl px-3 py-2.5 text-sm focus:outline-none" style={{...sel,outlineColor:t.inputFocus}} value={f.name} onChange={e=>u("name",e.target.value)} placeholder="Netflix, Spotify..."/></div>
        <div><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Category</label><select className="w-full rounded-xl px-3 py-2.5 text-sm" style={sel} value={f.category} onChange={e=>u("category",e.target.value)}>{CATS.map(c=><option key={c}>{c}</option>)}</select></div>
        <div><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Cost ($)</label><input type="number" step="0.01" min="0" className="w-full rounded-xl px-3 py-2.5 text-sm" style={sel} value={f.cost||""} onChange={e=>u("cost",+e.target.value)}/></div>
        <div><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Billing Cycle</label><select className="w-full rounded-xl px-3 py-2.5 text-sm" style={sel} value={f.cycle} onChange={e=>u("cycle",e.target.value)}>{CYCLES.map(c=><option key={c}>{c}</option>)}</select></div>
        <div><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Next Renewal</label><input type="date" className="w-full rounded-xl px-3 py-2.5 text-sm" style={sel} value={f.renewal} onChange={e=>u("renewal",e.target.value)}/></div>
        <div><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Status</label><select className="w-full rounded-xl px-3 py-2.5 text-sm" style={sel} value={f.status} onChange={e=>u("status",e.target.value)}>{STATUSES.map(c=><option key={c}>{c}</option>)}</select></div>
        <div><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Last Used</label><input type="date" className="w-full rounded-xl px-3 py-2.5 text-sm" style={sel} value={f.lastUsed} onChange={e=>u("lastUsed",e.target.value)}/></div>
        <div><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Usage Frequency</label><select className="w-full rounded-xl px-3 py-2.5 text-sm" style={sel} value={f.freq} onChange={e=>u("freq",e.target.value)}>{FREQS.map(c=><option key={c}>{c}</option>)}</select></div>
        <div><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Importance</label><select className="w-full rounded-xl px-3 py-2.5 text-sm" style={sel} value={f.importance} onChange={e=>u("importance",e.target.value)}>{IMPS.map(c=><option key={c}>{c}</option>)}</select></div>
        <div><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Cancel Difficulty</label><select className="w-full rounded-xl px-3 py-2.5 text-sm" style={sel} value={f.difficulty} onChange={e=>u("difficulty",e.target.value)}>{DIFFS.map(c=><option key={c}>{c}</option>)}</select></div>
        <div className="flex items-center gap-3"><label className="text-xs" style={{color:t.textMuted}}>Auto-Renew</label><input type="checkbox" checked={f.autoRenew} onChange={e=>u("autoRenew",e.target.checked)} className="accent-purple-500 w-4 h-4"/></div>
        <div className="flex items-center gap-3"><label className="text-xs" style={{color:t.textMuted}}>Free Alternative</label><input type="checkbox" checked={f.freeAlt} onChange={e=>u("freeAlt",e.target.checked)} className="accent-purple-500 w-4 h-4"/></div>
        <div className="sm:col-span-2"><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Account Link</label><input className="w-full rounded-xl px-3 py-2.5 text-sm" style={sel} value={f.link} onChange={e=>u("link",e.target.value)} placeholder="https://..."/></div>
        <div className="sm:col-span-2"><label className="text-xs mb-1 block" style={{color:t.textMuted}}>Notes</label><textarea className="w-full rounded-xl px-3 py-2.5 text-sm resize-none" style={sel} rows={2} value={f.notes} onChange={e=>u("notes",e.target.value)}/></div>
      </div>
      <div className="flex justify-end gap-3 mt-5">
        <button onClick={onCancel} className="px-4 py-2.5 rounded-xl text-sm transition hover:opacity-80" style={{color:t.textMuted,border:`1px solid ${t.cardBorder}`}}>Cancel</button>
        <button onClick={()=>{
          if(f.name.trim())onSave(f);
        }} className="px-6 py-2.5 rounded-xl text-sm font-bold bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-500 hover:to-blue-500 text-white disabled:opacity-40 transition shadow-lg shadow-purple-500/20" disabled={!f.name.trim()}>Save</button>
      </div>
    </div>
  </div>
}

type Tab="dashboard"|"table"|"analytics"|"mobile"|"detox"|"smart"|"intel"|"weekly";

export default function ZoScriptionHQ(){
  const[subs,save]=useSubs();
  const[light,setLight]=useTheme();
  const t=light?lightTheme:darkTheme;
  const[tab,setTab]=useState<Tab>("dashboard");
  const[editing,setEditing]=useState<Sub|null|"new">(null);
  const[search,setSearch]=useState("");
  const[sortCol,setSortCol]=useState<string>("name");
  const[sortDir,setSortDir]=useState<1|-1>(1);
  const[detoxActive,setDetoxActive]=useState(false);
  const[weeklyChecks,setWeeklyChecks]=useState<Record<string,boolean>>(()=>{try{return JSON.parse(localStorage.getItem("zosc_weekly")||"{}")}catch{return{}}});

  const active=useMemo(()=>subs.filter(s=>s.status==="Active"),[subs]);

  const totalMonthly=useMemo(()=>active.reduce((a,s)=>a+monthly(s),0),[active]);
  const totalYearly=useMemo(()=>active.reduce((a,s)=>a+yearly(s),0),[active]);

  const potentialSavings=useMemo(()=>active.filter(s=>wasteLevel(s)!=="Low").reduce((a,s)=>a+monthly(s),0),[active]);

  const renewals=useMemo(()=>{
    const td=today();
    return active.filter(s=>s.renewal>=td).sort((a,b)=>a.renewal.localeCompare(b.renewal)).map(s=>{
      const d=daysBetween(td,s.renewal);
      return{...s,days:d,urgency:d<=7?"red":d<=14?"yellow":"blue" as "red"|"yellow"|"blue"};
    });
  },[active]);

  const wasteGroups=useMemo(()=>{
    const h=active.filter(s=>wasteLevel(s)==="High");
    const m=active.filter(s=>wasteLevel(s)==="Medium");
    const l=active.filter(s=>wasteLevel(s)==="Low");
    return{high:h,medium:m,low:l};
  },[active]);

  const cancelRecs=useMemo(()=>active.map(s=>({sub:s,rec:recommendation(s),savings:monthly(s),reason:
    wasteLevel(s)==="High"?`Not used in ${daysBetween(s.lastUsed,today())}d, ${s.importance.toLowerCase()} importance${s.freeAlt?", free alt exists":""}`:
    wasteLevel(s)==="Medium"?`Usage is ${s.freq.toLowerCase()}, consider reviewing`:"Good value, active use"
  })).sort((a,b)=>wasteScore(b.sub)-wasteScore(a.sub)),[active]);

  const savingsScenarios=useMemo(()=>{
    const sorted=[...active].sort((a,b)=>wasteScore(b)-wasteScore(a));
    return[10,25,50].map(pct=>{
      const target=totalMonthly*(pct/100);let cut=0;const toCut:Sub[]=[];
      for(const s of sorted){if(cut>=target)break;toCut.push(s);cut+=monthly(s)}
      return{pct,toCut,saved:cut,newMonthly:totalMonthly-cut,newYearly:(totalMonthly-cut)*12};
    });
  },[active,totalMonthly]);

  const catSpend=useMemo(()=>{
    const m:Record<string,number>={};
    active.forEach(s=>{m[s.category]=(m[s.category]||0)+monthly(s)});
    return Object.entries(m).map(([label,value])=>({label,value,color:CAT_COLORS[label as Category]||"#6b7280"})).sort((a,b)=>b.value-a.value);
  },[active]);

  const costRank=useMemo(()=>[...active].sort((a,b)=>monthly(b)-monthly(a)).map(s=>({label:s.name,value:monthly(s),color:monthly(s)>30?"#ef4444":monthly(s)>15?"#eab308":"#22c55e"})),[active]);

  const scatterData=useMemo(()=>active.map(s=>({label:s.name,x:monthly(s),y:valueScore(s),color:VC[valueTier(s)]})),[active]);

  const detoxItems=useMemo(()=>{
    return active.map(s=>{
      const d=daysBetween(s.lastUsed,today());
      const risk=(d>14?1:0)+(s.freq==="Rarely"?1:0)+(s.importance==="Low"?1:0)+(s.freeAlt?1:0);
      const tier=risk>=3?"Cut Immediately":risk>=2?"Strong Consideration":risk>=1?"Keep Temporarily":"Safe Core";
      return{sub:s,risk,tier};
    }).sort((a,b)=>b.risk-a.risk);
  },[active]);

  const detoxScore=useMemo(()=>{
    const avg=detoxItems.length?detoxItems.reduce((a,d)=>a+d.risk,0)/detoxItems.length:0;
    return avg>=2?"Bloated":avg>=1?"Moderate":"Lean";
  },[detoxItems]);

  const minViable=useMemo(()=>detoxItems.filter(d=>d.tier==="Safe Core"||d.tier==="Keep Temporarily"),[detoxItems]);
  const maxSavings=useMemo(()=>detoxItems.filter(d=>d.tier==="Cut Immediately"||d.tier==="Strong Consideration").reduce((a,d)=>a+monthly(d.sub),0),[detoxItems]);

  function handleSave(s:Sub){
    const idx=subs.findIndex(x=>x.id===s.id);
    if(idx>=0){const n=[...subs];n[idx]=s;save(n)}else save([...subs,s]);
    setEditing(null);
  }
  function handleDelete(id:string){save(subs.filter(s=>s.id!==id))}
  function toggleWeekly(k:string){const n={...weeklyChecks,[k]:!weeklyChecks[k]};setWeeklyChecks(n);localStorage.setItem("zosc_weekly",JSON.stringify(n))}
  function resetWeekly(){setWeeklyChecks({});localStorage.removeItem("zosc_weekly")}

  const filtered=useMemo(()=>{
    let f=subs;
    if(search)f=f.filter(s=>s.name.toLowerCase().includes(search.toLowerCase())||s.category.toLowerCase().includes(search.toLowerCase()));
    return[...f].sort((a,b)=>{
      const av=sortCol==="cost"?monthly(a):sortCol==="renewal"?a.renewal:sortCol==="waste"?wasteScore(a):sortCol==="value"?valueScore(a):(a as any)[sortCol]||"";
      const bv=sortCol==="cost"?monthly(b):sortCol==="renewal"?b.renewal:sortCol==="waste"?wasteScore(b):sortCol==="value"?valueScore(b):(b as any)[sortCol]||"";
      if(typeof av==="number"&&typeof bv==="number")return(av-bv)*sortDir;
      return String(av).localeCompare(String(bv))*sortDir;
    });
  },[subs,search,sortCol,sortDir]);

  function toggleSort(col:string){if(sortCol===col)setSortDir(d=>d===1?-1:1);else{setSortCol(col);setSortDir(1)}}

  const tabs:{id:Tab,label:string,icon:React.ReactNode}[]=[
    {id:"dashboard",label:"Dashboard",icon:<BarChart3 className="w-4 h-4"/>},
    {id:"table",label:"Table",icon:<ListChecks className="w-4 h-4"/>},
    {id:"analytics",label:"Analytics",icon:<PieChart className="w-4 h-4"/>},
    {id:"mobile",label:"Quick Control",icon:<Smartphone className="w-4 h-4"/>},
    {id:"detox",label:"Detox",icon:<Zap className="w-4 h-4"/>},
    {id:"smart",label:"Smart Views",icon:<Eye className="w-4 h-4"/>},
    {id:"intel",label:"Intelligence",icon:<Brain className="w-4 h-4"/>},
    {id:"weekly",label:"Weekly",icon:<Calendar className="w-4 h-4"/>},
  ];

  const urgColor={red:"#ef4444",yellow:"#eab308",blue:"#3b82f6"};
  const detoxColor:Record<string,string>={"Cut Immediately":"#ef4444","Strong Consideration":"#f97316","Keep Temporarily":"#eab308","Safe Core":"#22c55e"};
  const detoxScoreColor:Record<string,string>={Bloated:"#ef4444",Moderate:"#eab308",Lean:"#22c55e"};

  const healthScore = useMemo(()=>{
    if(!active.length) return 100;
    const wasteRatio = wasteGroups.high.length / active.length;
    const valueRatio = active.filter(s=>valueTier(s)==="Excellent"||valueTier(s)==="Good").length / active.length;
    return Math.round(Math.max(0, Math.min(100, (1 - wasteRatio) * 50 + valueRatio * 50)));
  },[active, wasteGroups]);

  const healthColor = healthScore >= 75 ? "#22c55e" : healthScore >= 50 ? "#eab308" : "#ef4444";

  return <div className="min-h-screen transition-colors duration-300" style={{background:t.bg,color:t.text}}>
    <header className="max-w-7xl mx-auto flex items-center justify-between px-4 md:px-6 py-4" style={{borderBottom:`1px solid ${t.divider}`}}>
      <div className="flex items-center gap-3">
        <img src="/images/pegasus.png" alt="Zo" className="w-10 h-10 rounded-full object-contain" style={{background: "linear-gradient(135deg, #7c3aed, #3b82f6)"}} />
        <div>
          <h1 className="text-2xl font-bold bg-gradient-to-r from-purple-400 via-blue-400 to-cyan-400 bg-clip-text text-transparent">ZoScription HQ</h1>
          <p className="text-xs tracking-[0.25em] uppercase" style={{color:t.textMuted}}>Clarity over every subscription</p>
        </div>
      </div>
      <div className="flex items-center gap-2">
        <button onClick={()=>{
          const n=subs.map(s=>s.id===r.sub.id?{...s,status:"Active" as Status}:s);
          save(n);
        }} className="flex items-center gap-2 px-4 py-2.5 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-500 hover:to-blue-500 rounded-xl text-sm font-bold transition-all text-white shadow-lg shadow-purple-500/20 hover:shadow-purple-500/30 hover:scale-[1.02] active:scale-[0.98]">
          <Plus className="w-4 h-4"/>Add Subscription
        </button>
      </div>
    </header>

    <nav className="max-w-7xl mx-auto flex gap-1 px-4 md:px-6 py-3 overflow-x-auto" style={{borderBottom:`1px solid ${t.divider}`}}>
      {tabs.map(tb=><button key={tb.id} onClick={()=>{
        setTab(tb.id);
        if(tb.id==="table") setEditing(null);
      }} className={"flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-medium whitespace-nowrap transition-all "+(tab===tb.id?"text-white shadow-lg shadow-purple-500/20":"")} style={tab===tb.id?{background:"linear-gradient(135deg, #7c3aed, #3b82f6)"}:{color:t.textMuted}}>{tb.icon}{tb.label}</button>)}
    </nav>

    <main className="max-w-7xl mx-auto px-4 sm:px-6 py-6 space-y-6">

      {tab==="dashboard"&&<>
        <div className="grid grid-cols-2 lg:grid-cols-5 gap-3">
          <StatCard label="Monthly Spend" value={`$${totalMonthly.toFixed(2)}`} sub={`${active.length} active`} color="#3b82f6" t={t} icon={<BarChart3 className="w-5 h-5" style={{color:"#3b82f6"}}/>}/>
          <StatCard label="Yearly Cost" value={`$${totalYearly.toFixed(2)}`} color="#8b5cf6" t={t} icon={<Calendar className="w-5 h-5" style={{color:"#8b5cf6"}}/>}/>
          <StatCard label="Potential Savings" value={`$${potentialSavings.toFixed(2)}/mo`} sub={`$${(potentialSavings*12).toFixed(2)}/yr`} color="#22c55e" t={t} icon={<TrendingDown className="w-5 h-5" style={{color:"#22c55e"}}/>}/>
          <StatCard label="Waste Alerts" value={`${wasteGroups.high.length}`} sub={`${wasteGroups.medium.length} caution`} color="#ef4444" t={t} icon={<AlertTriangle className="w-5 h-5" style={{color:"#ef4444"}}/>}/>
          <StatCard label="Health Score" value={`${healthScore}`} sub={healthScore>=75?"Healthy":healthScore>=50?"Needs work":"Critical"} color={healthColor} t={t} icon={<Activity className="w-5 h-5" style={{color:healthColor}}/>}/>
        </div>

        <Card t={t}>
          <h3 className="text-sm font-bold mb-3 flex items-center gap-2" style={{color:t.textDim}}><AlertTriangle className="w-4 h-4 text-yellow-500"/>Renewal Watchlist</h3>
          {renewals.length===0?<p className="text-sm" style={{color:t.textFaint}}>No upcoming renewals</p>:
          <div className="space-y-2">{renewals.slice(0,8).map(r=><div key={r.id} className="flex items-center justify-between py-2.5 px-4 rounded-xl transition hover:scale-[1.005]" style={{background:urgColor[r.urgency]+"0d",borderLeft:`3px solid ${urgColor[r.urgency]}`}}>
            <div className="flex items-center gap-2"><span className="text-base">{CAT_ICONS[r.category]}</span><span className="text-sm font-medium" style={{color:t.text}}>{r.name}</span><span className="text-xs" style={{color:t.textMuted}}>{r.category}</span></div>
            <div className="text-right flex items-center gap-3"><span className="text-xs font-bold px-2 py-0.5 rounded-full" style={{background:urgColor[r.urgency]+"22",color:urgColor[r.urgency]}}>{r.days}d</span><span className="text-xs font-mono" style={{color:t.textMuted}}>${monthly(r).toFixed(2)}/mo</span></div>
          </div>)}</div>}
        </Card>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
          {(["high","medium","low"] as const).map(level=><Card key={level} t={t}>
            <h3 className="text-sm font-bold mb-3 flex items-center gap-2" style={{color:WC[level==="high"?"High":level==="medium"?"Medium":"Low"]}}><span className="w-2.5 h-2.5 rounded-full" style={{background:WC[level==="high"?"High":level==="medium"?"Medium":"Low"]}}/>{level==="high"?"High Waste":level==="medium"?"Medium Waste":"Low Waste"} ({wasteGroups[level].length})</h3>
            {wasteGroups[level].length===0?<p className="text-xs" style={{color:t.textFaint}}>None</p>:
            <div className="space-y-1.5">{wasteGroups[level].map(s=><div key={s.id} className="flex justify-between items-center text-xs py-1.5 px-2 rounded-lg transition" style={{background:t.hoverBg}}><span className="flex items-center gap-1.5" style={{color:t.textDim}}><span>{CAT_ICONS[s.category]}</span>{s.name}</span><span className="text-xs font-mono" style={{color:t.textMuted}}>${monthly(s).toFixed(2)}/mo</span></div>)}</div>}
          </Card>)}
        </div>

        <Card t={t}>
          <h3 className="text-sm font-bold mb-3 flex items-center gap-2" style={{color:t.textDim}}><XCircle className="w-4 h-4 text-red-500"/>Cancellation Recommendations</h3>
          <div className="space-y-2">{cancelRecs.slice(0,8).map(r=><div key={r.sub.id} className="flex flex-col sm:flex-row sm:items-center justify-between py-3 px-4 rounded-xl" style={{background:RC[r.rec]+"0d",borderLeft:`3px solid ${RC[r.rec]}`}}>
            <div className="flex items-center gap-2"><Badge color={RC[r.rec]}>{r.rec.toUpperCase()}</Badge><span className="text-sm font-medium" style={{color:t.text}}>{r.sub.name}</span></div>
            <div className="flex items-center gap-3 mt-1 sm:mt-0"><span className="text-xs" style={{color:t.textMuted}}>{r.reason}</span><span className="text-xs font-bold text-green-400 bg-green-400/10 px-2 py-0.5 rounded-full">Save ${r.savings.toFixed(2)}/mo</span></div>
          </div>)}</div>
        </Card>

        <Card t={t} className="border-purple-500/20">
          <h3 className="text-sm font-bold text-purple-400 mb-4 flex items-center gap-2"><TrendingDown className="w-4 h-4"/>Savings Scenarios</h3>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">{savingsScenarios.map(sc=><div key={sc.pct} className="rounded-xl p-5 transition hover:scale-[1.02]" style={{background:t.hoverBg,border:`1px solid ${t.cardBorder}`}}>
            <p className="text-3xl font-black bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">{sc.pct}%</p>
            <p className="text-[10px] uppercase tracking-widest mt-1" style={{color:t.textMuted}}>reduction</p>
            <p className="text-xs mt-1" style={{color:t.textFaint}}>Cancel {sc.toCut.length} subs</p>
            <div className="mt-4 space-y-1">
              <p className="text-sm"><span className="text-green-400 font-bold">Save ${sc.saved.toFixed(2)}/mo</span></p>
              <p className="text-xs" style={{color:t.textMuted}}>New: ${sc.newMonthly.toFixed(2)}/mo · ${sc.newYearly.toFixed(2)}/yr</p>
            </div>
            <div className="mt-3 space-y-0.5">{sc.toCut.slice(0,5).map(s=><p key={s.id} className="text-xs text-red-400">✕ {s.name}</p>)}{sc.toCut.length>5&&<p className="text-xs" style={{color:t.textFaint}}>+{sc.toCut.length-5} more</p>}</div>
          </div>)}</div>
        </Card>
      </>}

      {tab==="table"&&<>
        <div className="flex flex-col sm:flex-row gap-3 items-start sm:items-center justify-between">
          <div className="relative flex-1 max-w-sm"><Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2" style={{color:t.textMuted}}/><input className="w-full rounded-xl pl-9 pr-3 py-2.5 text-sm focus:outline-none transition" style={{background:t.inputBg,border:`1px solid ${t.inputBorder}`,color:t.text}} placeholder="Search subscriptions..." value={search} onChange={e=>setSearch(e.target.value)}/></div>
          <p className="text-xs" style={{color:t.textMuted}}>{filtered.length} subscriptions</p>
        </div>
        <div className="overflow-x-auto rounded-2xl transition" style={{border:`1px solid ${t.cardBorder}`}}>
          <table className="w-full text-xs">
            <thead><tr style={{background:t.card}}>
              {[{k:"name",l:"Service"},{k:"category",l:"Cat"},{k:"cost",l:"Cost/Mo"},{k:"cycle",l:"Cycle"},{k:"renewal",l:"Renewal"},{k:"status",l:"Status"},{k:"freq",l:"Usage"},{k:"importance",l:"Imp"},{k:"waste",l:"Waste"},{k:"value",l:"Value"},{k:"",l:""}].map(c=>
                <th key={c.k||c.l} className="px-3 py-3 text-left cursor-pointer whitespace-nowrap uppercase tracking-wider text-[10px] font-medium transition hover:opacity-80" style={{color:t.textMuted}} onClick={()=>{
                  if(c.k) toggleSort(c.k);
                }}>
                  <span className="flex items-center gap-1">{c.l}{sortCol===c.k&&(sortDir===1?<ChevronUp className="w-3 h-3"/>:<ChevronDown className="w-3 h-3"/>)}</span>
                </th>)}
            </tr></thead>
            <tbody>{filtered.map(s=><tr key={s.id} className="transition hover:brightness-110" style={{borderBottom:`1px solid ${t.divider}`}}>
              <td className="px-3 py-3 font-medium whitespace-nowrap" style={{color:t.textDim}}><span className="mr-1.5">{CAT_ICONS[s.category]}</span>{s.name}{s.link&&<a href={s.link} target="_blank" rel="noreferrer" className="ml-1 inline-block"><ExternalLink className="w-3 h-3 hover:text-blue-400" style={{color:t.textFaint}}/></a>}</td>
              <td className="px-3 py-3"><span className="px-1.5 py-0.5 rounded text-[10px] font-medium" style={{background:CAT_COLORS[s.category]+"22",color:CAT_COLORS[s.category]}}>{s.category}</span></td>
              <td className="px-3 py-3 font-mono font-medium" style={{color:t.textDim}}>${monthly(s).toFixed(2)}</td>
              <td className="px-3 py-3" style={{color:t.textMuted}}>{s.cycle}</td>
              <td className="px-3 py-3" style={{color:t.textMuted}}>{s.renewal}</td>
              <td className="px-3 py-3"><Badge color={s.status==="Active"?"#22c55e":s.status==="Paused"?"#eab308":"#ef4444"}>{s.status}</Badge></td>
              <td className="px-3 py-3" style={{color:t.textMuted}}>{s.freq}</td>
              <td className="px-3 py-3"><Badge color={s.importance==="High"?"#22c55e":s.importance==="Medium"?"#eab308":"#ef4444"}>{s.importance}</Badge></td>
              <td className="px-3 py-3"><Badge color={WC[wasteLevel(s)]}>{wasteLevel(s)}</Badge></td>
              <td className="px-3 py-3"><Badge color={VC[valueTier(s)]}>{valueTier(s)}</Badge></td>
              <td className="px-3 py-3"><div className="flex gap-1">
                <button onClick={()=>{
                  const n=subs.map(s=>s.id===r.sub.id?{...s,status:"Active" as Status}:s);
                  save(n);
                }} className="p-1.5 rounded-lg transition hover:scale-110" style={{color:t.textMuted}}><Edit3 className="w-3.5 h-3.5 hover:text-blue-400"/></button>
                <button onClick={()=>{
                  const n=subs.map(s=>s.id===r.sub.id?{...s,status:"Cancelled" as Status}:s);
                  save(n);
                }} className="p-1.5 rounded-lg transition hover:scale-110" style={{color:t.textMuted}}><Trash2 className="w-3.5 h-3.5 hover:text-red-400"/></button>
              </div></td>
            </tr>)}</tbody>
          </table>
          {filtered.length===0&&<p className="text-center py-12 text-sm" style={{color:t.textFaint}}>No subscriptions yet. Add one above.</p>}
        </div>
      </>}

      {tab==="analytics"&&<>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <Card t={t}><h3 className="text-sm font-bold mb-1" style={{color:t.textDim}}>Category Spend</h3><p className="text-xs mb-4" style={{color:t.textFaint}}>Monthly cost breakdown by category</p><PieChartSVG data={catSpend} t={t}/>{catSpend[0]&&<p className="text-xs mt-3" style={{color:t.textMuted}}>Largest: {catSpend[0].label} at ${catSpend[0].value.toFixed(2)}/mo</p>}</Card>
          <Card t={t}><h3 className="text-sm font-bold mb-1" style={{color:t.textDim}}>Cost by Subscription</h3><p className="text-xs mb-4" style={{color:t.textFaint}}>Ranked highest to lowest monthly cost</p><BarChartSVG data={costRank} t={t}/>{costRank[0]&&<p className="text-xs mt-3" style={{color:t.textMuted}}>Top spender: {costRank[0].label} at ${costRank[0].value.toFixed(2)}/mo</p>}</Card>
          <Card t={t}><h3 className="text-sm font-bold mb-1" style={{color:t.textDim}}>Value vs Cost</h3><p className="text-xs mb-4" style={{color:t.textFaint}}>Top-left = best value. Bottom-right = review.</p><ScatterSVG data={scatterData} t={t}/></Card>
          <Card t={t}><h3 className="text-sm font-bold mb-1" style={{color:t.textDim}}>Renewal Timeline</h3><p className="text-xs mb-4" style={{color:t.textFaint}}>Upcoming renewals color-coded by urgency</p>
            {renewals.length===0?<p className="text-sm" style={{color:t.textFaint}}>No upcoming renewals</p>:
            <div className="space-y-2">{renewals.slice(0,12).map(r=><div key={r.id} className="flex items-center gap-2">
              <div className="w-2.5 h-2.5 rounded-full shrink-0" style={{background:urgColor[r.urgency]}}/>
              <div className="flex-1 h-7 rounded-full relative overflow-hidden" style={{background:urgColor[r.urgency]+"12"}}>
                <div className="absolute inset-y-0 left-0 rounded-full" style={{width:`${Math.max(5,100-r.days*2)}%`,background:urgColor[r.urgency]+"25"}}/>
                <span className="absolute inset-0 flex items-center px-3 text-[11px] font-medium" style={{color:t.textDim}}>{r.name} — {r.days}d — ${monthly(r).toFixed(2)}/mo</span>
              </div>
            </div>)}</div>}
          </Card>
          <Card t={t} className="md:col-span-2"><h3 className="text-sm font-bold mb-1" style={{color:t.textDim}}>Savings Opportunities</h3><p className="text-xs mb-4" style={{color:t.textFaint}}>Potential monthly savings per subscription</p>
            <BarChartSVG data={active.filter(s=>wasteLevel(s)!=="Low").sort((a,b)=>monthly(b)-monthly(a)).map(s=>({label:s.name,value:monthly(s),color:WC[wasteLevel(s)]}))} height={160} t={t}/>
            <p className="text-xs mt-3" style={{color:t.textMuted}}>Total potential: ${potentialSavings.toFixed(2)}/mo · ${(potentialSavings*12).toFixed(2)}/yr</p>
          </Card>
        </div>
      </>}

      {tab==="mobile"&&<div className="max-w-sm mx-auto space-y-4">
        <div className="text-center py-8">
          <p className="text-[10px] uppercase tracking-[0.2em] font-medium" style={{color:t.textMuted}}>Monthly Spend</p>
          <p className="text-6xl font-black bg-gradient-to-b from-blue-400 to-blue-600 bg-clip-text text-transparent mt-2">${totalMonthly.toFixed(2)}</p>
          <p className="text-xs mt-2" style={{color:t.textFaint}}>${totalYearly.toFixed(2)}/yr</p>
          <div className="mt-4 flex justify-center"><div className="px-3 py-1 rounded-full text-xs font-bold" style={{background:healthColor+"22",color:healthColor}}>Health: {healthScore}/100</div></div>
        </div>

        <Card t={t}>
          <h3 className="text-[10px] font-bold uppercase tracking-widest mb-3" style={{color:t.textMuted}}>Top Actions</h3>
          {cancelRecs.slice(0,3).map(r=><div key={r.sub.id} className="flex items-center justify-between py-3" style={{borderBottom:`1px solid ${t.divider}`}}>
            <div><p className="text-sm font-medium" style={{color:t.text}}>{r.sub.name}</p><p className="text-xs" style={{color:t.textMuted}}>${monthly(r.sub).toFixed(2)}/mo</p></div>
            <div className="flex gap-1.5">
              <button onClick={()=>{
                const n=subs.map(s=>s.id===r.sub.id?{...s,status:"Active" as Status}:s);
                save(n);
              }} className="px-3 py-2 rounded-xl text-[10px] font-bold bg-green-500/10 text-green-400 border border-green-500/20 hover:bg-green-500/20 transition active:scale-95">KEEP</button>
              <button onClick={()=>{
                const n=subs.map(s=>s.id===r.sub.id?{...s,status:"Cancelled" as Status}:s);
                save(n);
              }} className="px-3 py-2 rounded-xl text-[10px] font-bold bg-red-500/10 text-red-400 border border-red-500/20 hover:bg-red-500/20 transition active:scale-95">CANCEL</button>
            </div>
          </div>)}
          {cancelRecs.length===0&&<p className="text-sm text-center py-4" style={{color:t.textFaint}}>No subscriptions</p>}
        </Card>

        <Card t={t}>
          <h3 className="text-[10px] font-bold uppercase tracking-widest mb-3" style={{color:t.textMuted}}>Next Renewals</h3>
          {renewals.slice(0,3).map(r=><div key={r.id} className="flex items-center justify-between py-2.5" style={{borderBottom:`1px solid ${t.divider}`}}>
            <span className="text-sm" style={{color:t.text}}>{CAT_ICONS[r.category]} {r.name}</span>
            <div className="text-right"><span className="text-xs font-bold px-2 py-0.5 rounded-full" style={{background:urgColor[r.urgency]+"22",color:urgColor[r.urgency]}}>{r.days}d</span><span className="text-xs ml-2 font-mono" style={{color:t.textMuted}}>${monthly(r).toFixed(2)}</span></div>
          </div>)}
          {renewals.length===0&&<p className="text-sm text-center py-4" style={{color:t.textFaint}}>No upcoming renewals</p>}
        </Card>
      </div>}

      {tab==="detox"&&<>
        <div className="flex items-center justify-between">
          <div><h2 className="text-lg font-bold" style={{color:t.text}}>Subscription Detox</h2><p className="text-xs" style={{color:t.textMuted}}>Identify and eliminate subscription bloat</p></div>
          <button onClick={()=>{
            const n=subs.map(s=>s.id===r.sub.id?{...s,status:"Active" as Status}:s);
            save(n);
          }} className="px-5 py-2.5 rounded-xl text-sm font-bold transition-all shadow-lg hover:scale-[1.02] active:scale-[0.98] text-white bg-gradient-to-r from-purple-600 to-blue-600 shadow-purple-500/20">Activate Detox</button>
        </div>
        {detoxActive&&<>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            <StatCard label="Detox Score" value={detoxScore} color={detoxScoreColor[detoxScore]} t={t}/>
            <StatCard label="Max Savings" value={`$${maxSavings.toFixed(2)}/mo`} color="#22c55e" t={t}/>
            <StatCard label="Min Viable Set" value={`${minViable.length}`} sub="subscriptions" color="#3b82f6" t={t}/>
            <StatCard label="Flagged" value={`${detoxItems.filter(d=>d.risk>=2).length}`} sub="high risk" color="#ef4444" t={t}/>
          </div>
          {["Cut Immediately","Strong Consideration","Keep Temporarily","Safe Core"].map(tier=>{
            const items=detoxItems.filter(d=>d.tier===tier);
            if(!items.length)return null;
            return <Card key={tier} t={t}>
              <h3 className="text-sm font-bold mb-3 flex items-center gap-2" style={{color:detoxColor[tier]}}><span className="w-2.5 h-2.5 rounded-full" style={{background:detoxColor[tier]}}/>{tier} ({items.length})</h3>
              <div className="space-y-1.5">{items.map(d=><div key={d.sub.id} className="flex items-center justify-between py-2 px-3 rounded-lg text-xs transition" style={{background:detoxColor[tier]+"08"}}>
                <div className="flex items-center gap-2"><span>{CAT_ICONS[d.sub.category]}</span><span style={{color:t.textDim}}>{d.sub.name}</span><span style={{color:t.textFaint}}>{d.sub.category}</span></div>
                <span className="font-mono" style={{color:t.textMuted}}>${monthly(d.sub).toFixed(2)}/mo</span>
              </div>)}</div>
            </Card>
          })}
        </>}
        {!detoxActive&&<Card t={t} className="text-center py-16"><div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-purple-600 to-blue-600 flex items-center justify-center mx-auto mb-4 shadow-lg shadow-purple-500/20"><Zap className="w-8 h-8 text-white"/></div><p className="text-sm" style={{color:t.textMuted}}>Activate Detox Mode to analyze your subscription bloat</p></Card>}
      </>}

      {tab==="smart"&&<>
        {[
          {title:"Wasted Money",emoji:"🔴",desc:"High waste, low value subscriptions",items:active.filter(s=>wasteLevel(s)==="High"),color:"#ef4444"},
          {title:"Renewing Soon",emoji:"🟡",desc:"Renewals in the next 14 days",items:renewals.filter(r=>r.days<=14).map(r=>active.find(s=>s.id===r.id)!).filter(Boolean),color:"#eab308"},
          {title:"High Cost",emoji:"🔴",desc:"Subscriptions over $25/mo",items:active.filter(s=>monthly(s)>25).sort((a,b)=>monthly(b)-monthly(a)),color:"#ef4444"},
          {title:"Low Value",emoji:"🔴",desc:"Weak value tier subscriptions",items:active.filter(s=>valueTier(s)==="Weak"),color:"#ef4444"},
          {title:"Best Value",emoji:"🟢",desc:"Excellent value subscriptions",items:active.filter(s=>valueTier(s)==="Excellent"),color:"#22c55e"},
          {title:"Free Alternatives",emoji:"🟣",desc:"Paid subs with free alternatives available",items:active.filter(s=>s.freeAlt),color:"#a855f7"},
        ].map(v=><Card key={v.title} t={t}>
          <h3 className="text-sm font-bold flex items-center gap-2" style={{color:v.color}}>{v.emoji} {v.title} <span className="text-xs font-normal" style={{color:t.textFaint}}>({v.items.length})</span></h3>
          <p className="text-xs mb-3" style={{color:t.textFaint}}>{v.desc}</p>
          {v.items.length===0?<p className="text-xs" style={{color:t.textFaint}}>None found</p>:
          <div className="space-y-1">{v.items.map(s=><div key={s.id} className="flex justify-between text-xs py-2 px-2 rounded-lg transition" style={{background:v.color+"08",borderBottom:`1px solid ${t.divider}`}}><span style={{color:t.textDim}}>{CAT_ICONS[s.category]} {s.name}<span className="ml-2" style={{color:t.textFaint}}>{s.category}</span></span><span className="font-mono" style={{color:t.textMuted}}>${monthly(s).toFixed(2)}/mo</span></div>)}</div>}
        </Card>)}
      </>}

      {tab==="intel"&&<>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <Card t={t} className="border-red-500/20">
            <h3 className="text-sm font-bold text-red-400 flex items-center gap-2"><XCircle className="w-4 h-4"/>Top 3 to Cancel</h3>
            <div className="mt-3 space-y-2">{cancelRecs.filter(r=>r.rec==="cancel").slice(0,3).map((r,i)=><div key={r.sub.id} className="flex justify-between items-center py-3 px-4 rounded-xl" style={{background:"#ef444408",border:"1px solid #ef444415"}}>
              <div><span className="text-sm font-medium" style={{color:t.text}}>{i+1}. {r.sub.name}</span><p className="text-xs mt-0.5" style={{color:t.textMuted}}>{r.reason}</p></div>
              <span className="text-sm font-bold text-green-400 bg-green-400/10 px-2 py-1 rounded-lg">-${r.savings.toFixed(2)}/mo</span>
            </div>)}{cancelRecs.filter(r=>r.rec==="cancel").length===0&&<p className="text-xs" style={{color:t.textFaint}}>No cancellations needed 🎉</p>}</div>
          </Card>
          <Card t={t} className="border-green-500/20">
            <h3 className="text-sm font-bold text-green-400 flex items-center gap-2"><CheckCircle className="w-4 h-4"/>Top 3 to Keep</h3>
            <div className="mt-3 space-y-2">{[...active].sort((a,b)=>valueScore(b)-valueScore(a)).slice(0,3).map((s,i)=><div key={s.id} className="flex justify-between items-center py-3 px-4 rounded-xl" style={{background:"#22c55e08",border:"1px solid #22c55e15"}}>
              <div><span className="text-sm font-medium" style={{color:t.text}}>{i+1}. {s.name}</span><p className="text-xs mt-0.5" style={{color:t.textMuted}}>{s.freq} use, {s.importance.toLowerCase()} importance</p></div>
              <Badge color="#22c55e">{valueTier(s)}</Badge>
            </div>)}</div>
          </Card>
          <Card t={t} className="border-yellow-500/20">
            <h3 className="text-sm font-bold text-yellow-400 flex items-center gap-2"><AlertTriangle className="w-4 h-4"/>Hidden Costs</h3>
            <div className="mt-3 space-y-2">
              {active.filter(s=>s.autoRenew&&wasteLevel(s)!=="Low").slice(0,5).map(s=><div key={s.id} className="flex justify-between text-xs py-2 px-3 rounded-lg" style={{background:"#eab30808"}}>
                <span style={{color:t.textDim}}>{s.name} <span style={{color:t.textFaint}}>(auto-renew, {wasteLevel(s).toLowerCase()} waste)</span></span>
                <span className="text-yellow-400 font-mono font-bold">${monthly(s).toFixed(2)}/mo</span>
              </div>)}
              {active.filter(s=>s.autoRenew&&wasteLevel(s)!=="Low").length===0&&<p className="text-xs" style={{color:t.textFaint}}>No hidden costs detected</p>}
            </div>
          </Card>
          <Card t={t} className="border-purple-500/20">
            <h3 className="text-sm font-bold text-purple-400 flex items-center gap-2"><Activity className="w-4 h-4"/>Optimization Plan</h3>
            <div className="mt-3 space-y-4">
              <div className="flex items-start gap-3"><div className="w-6 h-6 rounded-full bg-red-500/10 flex items-center justify-center text-red-400 text-xs font-bold shrink-0">1</div><div><p className="text-xs" style={{color:t.textMuted}}>Cancel high-waste subscriptions</p><p className="text-xs text-purple-400 font-bold mt-0.5">Save ${wasteGroups.high.reduce((a,s)=>a+monthly(s),0).toFixed(2)}/mo</p></div></div>
              <div className="flex items-start gap-3"><div className="w-6 h-6 rounded-full bg-yellow-500/10 flex items-center justify-center text-yellow-400 text-xs font-bold shrink-0">2</div><div><p className="text-xs" style={{color:t.textMuted}}>Review medium-waste items</p><p className="text-xs text-purple-400 font-bold mt-0.5">{wasteGroups.medium.length} to review</p></div></div>
              <div className="flex items-start gap-3"><div className="w-6 h-6 rounded-full bg-blue-500/10 flex items-center justify-center text-blue-400 text-xs font-bold shrink-0">3</div><div><p className="text-xs" style={{color:t.textMuted}}>Switch to free alternatives</p><p className="text-xs text-purple-400 font-bold mt-0.5">Save ${active.filter(s=>s.freeAlt).reduce((a,s)=>a+monthly(s),0).toFixed(2)}/mo</p></div></div>
              <div className="pt-3" style={{borderTop:`1px solid ${t.divider}`}}><p className="text-xs" style={{color:t.textMuted}}>Total optimization potential</p><p className="text-xl font-black bg-gradient-to-r from-purple-400 to-blue-400 bg-clip-text text-transparent">${potentialSavings.toFixed(2)}/mo · ${(potentialSavings*12).toFixed(2)}/yr</p></div>
            </div>
          </Card>
        </div>

        <Card t={t}>
          <h3 className="text-sm font-bold mb-4" style={{color:t.textDim}}>Value Score Breakdown</h3>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
            {(["Excellent","Good","Fair","Weak"] as const).map(tier=>{
              const items=active.filter(s=>valueTier(s)===tier);
              return <div key={tier} className="rounded-xl p-4 transition hover:scale-[1.02]" style={{background:VC[tier]+"08",border:`1px solid ${VC[tier]}22`}}>
                <p className="text-xs font-bold" style={{color:VC[tier]}}>{tier}</p>
                <p className="text-3xl font-black mt-1" style={{color:t.text}}>{items.length}</p>
                <div className="mt-2 space-y-0.5">{items.slice(0,3).map(s=><p key={s.id} className="text-[10px] truncate" style={{color:t.textMuted}}>{s.name}</p>)}{items.length>3&&<p className="text-[10px]" style={{color:t.textFaint}}>+{items.length-3} more</p>}</div>
              </div>
            })}
          </div>
        </Card>
      </>}

      {tab==="weekly"&&<div className="max-w-lg mx-auto space-y-4">
        <Card t={t}>
          <div className="flex justify-between items-center mb-5"><h3 className="text-sm font-bold" style={{color:t.textDim}}><span className="w-4 h-4 rounded-full bg-red-400/10 flex items-center justify-center text-red-400 text-xs font-bold shrink-0">•</span> Weekly Review Checklist</h3><button onClick={resetWeekly} className="text-xs transition hover:opacity-80" style={{color:t.textFaint}}>Reset</button></div>
          {[
            {k:"lastUsed",label:"Update 'Last Used' dates for active subscriptions"},
            {k:"renewals",label:"Check upcoming renewals (next 14 days)"},
            {k:"review",label:"Review 1 subscription for cancellation"},
            {k:"decide",label:"Confirm keep / cancel decision on flagged items"},
          ].map(item=><label key={item.k} className="flex items-start gap-3 py-3 cursor-pointer group transition rounded-xl px-2 hover:scale-[1.01]" style={{borderBottom:`1px solid ${t.divider}`}}>
            <div className="mt-0.5 w-5 h-5 rounded-md flex items-center justify-center shrink-0 transition" style={{background:weeklyChecks[item.k]?"#a855f7":t.inputBg,border:`1.5px solid ${weeklyChecks[item.k]?"#a855f7":t.inputBorder}`}}>
              {weeklyChecks[item.k]&&<CheckCircle className="w-3.5 h-3.5 text-white"/>}
            </div>
            <span className={"text-sm transition "+(weeklyChecks[item.k]?"line-through":"")} style={{color:weeklyChecks[item.k]?t.textFaint:t.textDim}}>{item.label}</span>
          </label>)}
          <div className="mt-5 pt-3" style={{borderTop:`1px solid ${t.divider}`}}>
            <div className="flex justify-between items-center mb-2"><p className="text-xs font-medium" style={{color:t.textMuted}}>{Object.values(weeklyChecks).filter(Boolean).length}/4 complete</p><p className="text-xs font-bold" style={{color:Object.values(weeklyChecks).filter(Boolean).length===4?"#22c55e":"#a855f7"}}>{Math.round((Object.values(weeklyChecks).filter(Boolean).length/4)*100)}%</p></div>
            <div className="w-full h-2 rounded-full overflow-hidden" style={{background:t.barBg}}>
              <div className="h-full rounded-full transition-all bg-gradient-to-r from-purple-500 to-blue-500" style={{width:`${(Object.values(weeklyChecks).filter(Boolean).length/4)*100}%`}}/>
            </div>
          </div>
        </Card>
        <div className="grid grid-cols-2 gap-3">
          <Card t={t}><h3 className="text-xs font-bold text-red-400 mb-3 flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-red-400"/>New Risks</h3>
            {wasteGroups.high.length?wasteGroups.high.slice(0,3).map(s=><p key={s.id} className="text-xs py-1" style={{color:t.textMuted}}>{CAT_ICONS[s.category]} {s.name}</p>):<p className="text-xs" style={{color:t.textFaint}}>None 🎉</p>}
          </Card>
          <Card t={t}><h3 className="text-xs font-bold text-green-400 mb-3 flex items-center gap-2"><span className="w-2 h-2 rounded-full bg-green-400"/>Improvements</h3>
            {active.filter(s=>valueTier(s)==="Excellent").length?active.filter(s=>valueTier(s)==="Excellent").slice(0,3).map(s=><p key={s.id} className="text-xs py-1" style={{color:t.textMuted}}>{CAT_ICONS[s.category]} {s.name}</p>):<p className="text-xs" style={{color:t.textFaint}}>Keep optimizing</p>}
          </Card>
        </div>
      </div>}

    </main>

    <footer className="text-center py-8 mt-8" style={{borderTop:`1px solid ${t.cardBorder}`}}>
      <p className="text-xs" style={{color:t.textMuted}}>Built by <span className="font-semibold bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent">DaGreatGAWDNYC</span></p>
      <p className="text-xs mt-1" style={{color:t.textMuted}}>Built with <span className="font-semibold bg-gradient-to-r from-blue-400 to-cyan-400 bg-clip-text text-transparent">Zo Computer</span></p>
      <p className="text-xs mt-1" style={{color:t.textFaint}}>⢕⣿⢀⣏⣿⢳⡕⣆⢺⣋⢟</p>
    </footer>

    {editing!==null&&<SubForm sub={editing==="new"?null:editing} onSave={handleSave} onCancel={()=>{
      const n=subs.map(s=>s.id===r.sub.id?{...s,status:"Active" as Status}:s);
      save(n);
    }} t={t}/>}
  </div>
}
